export interface GlossaryTerm {
  term: string;
  acronym?: string;
  category: "Physics & Solid-State" | "Devices" | "VLSI & Circuits" | "Fabrication" | "Packaging";
  definition: string;
  formula?: string;
  relatedTerms: string[];
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  {
    term: "Bandgap Energy",
    acronym: "Eg",
    category: "Physics & Solid-State",
    definition: "The energy difference between the top of the valence band and the bottom of the conduction band in a semiconductor where electrons cannot exist in stationary states (Silicon Eg = 1.12 eV, GaAs = 1.42 eV, GaN = 3.4 eV at 300K).",
    formula: "Eg = Ec - Ev",
    relatedTerms: ["Valence Band", "Conduction Band", "Fermi Level"]
  },
  {
    term: "Built-in Potential",
    acronym: "Vbi",
    category: "Devices",
    definition: "The electrostatic potential barrier developed across a metallurgical p-n junction in thermal equilibrium due to uncompensated ionized donor and acceptor space charges.",
    formula: "Vbi = (kT/q) · ln(Na · Nd / ni²)",
    relatedTerms: ["Depletion Region", "Poisson's Equation", "PN Junction"]
  },
  {
    term: "Drain-Induced Barrier Lowering",
    acronym: "DIBL",
    category: "Devices",
    definition: "A severe short-channel effect where applying high drain-to-source voltage (VDS) lowers the electrostatic potential barrier at the source, causing threshold voltage reduction and increased subthreshold leakage.",
    formula: "DIBL = (Vth_low_vds - Vth_high_vds) / (VDS_high - VDS_low)",
    relatedTerms: ["Threshold Voltage", "Short-Channel Effects", "FinFET"]
  },
  {
    term: "Fermi Level",
    acronym: "Ef",
    category: "Physics & Solid-State",
    definition: "The electrochemical potential of electrons in a solid representing the energy level at which the probability of electron occupancy is exactly 50% according to the Fermi-Dirac distribution.",
    formula: "f(E) = 1 / [ 1 + exp((E - Ef) / kT) ]",
    relatedTerms: ["Fermi-Dirac Statistics", "Intrinsic Carrier Density", "Doping"]
  },
  {
    term: "FinFET",
    acronym: "FinFET",
    category: "Devices",
    definition: "A 3D non-planar transistor architecture where a thin vertical silicon fin is wrapped on three sides by the gate electrode to suppress short-channel effects and subthreshold leakage.",
    relatedTerms: ["GAAFET", "Tri-Gate", "High-k Metal Gate"]
  },
  {
    term: "Gate-All-Around FET",
    acronym: "GAAFET",
    category: "Devices",
    definition: "An advanced transistor architecture where the gate electrode surrounds horizontally stacked silicon nanosheets on all 4 sides (100% perimeter wrap), providing near-ideal electrostatic channel control.",
    relatedTerms: ["FinFET", "Nanosheet", "Subthreshold Swing"]
  },
  {
    term: "High-k Dielectric",
    acronym: "HKMG",
    category: "Fabrication",
    definition: "Dielectric materials (such as Hafnium Dioxide HfO2, εr ≈ 25) with a high dielectric constant used to replace traditional SiO2 (εr = 3.9), allowing physically thicker films that prevent quantum tunneling leakage while maintaining high gate capacitance.",
    formula: "EOT = tox · (ε_sio2 / ε_highk)",
    relatedTerms: ["Equivalent Oxide Thickness", "Quantum Tunneling", "MOS Capacitor"]
  },
  {
    term: "Static Timing Analysis",
    acronym: "STA",
    category: "VLSI & Circuits",
    definition: "An exhaustive EDA verification method that validates all timing paths in a synchronous digital design across all process corners without requiring test vector simulations.",
    formula: "Setup Slack = Tclk + Tskew - (Tcq + Tcomb + Tsetup) ≥ 0",
    relatedTerms: ["Clock Tree Synthesis", "Setup Time", "Hold Time"]
  },
  {
    term: "Subthreshold Swing",
    acronym: "SS",
    category: "Devices",
    definition: "The gate voltage required to change the subthreshold drain current by one decade (10×). Thermodynamic limit at room temperature is ~60 mV/decade.",
    formula: "SS = ln(10) · (kT/q) · [ 1 + Cdep/Cox ]",
    relatedTerms: ["Subthreshold Leakage", "MOSFET", "Boltzmann Tyranny"]
  },
  {
    term: "Two-Dimensional Electron Gas",
    acronym: "2DEG",
    category: "Devices",
    definition: "A sheet of electrons free to move in two spatial dimensions but quantum-confined in the third, formed at the AlGaN/GaN heterojunction interface with ultra-high mobility exceeding 2000 cm²/V·s.",
    relatedTerms: ["GaN HEMT", "Heterostructure", "Mobility"]
  },
  {
    term: "Extreme Ultraviolet Lithography",
    acronym: "EUV",
    category: "Fabrication",
    definition: "Next-generation semiconductor photolithography utilizing 13.5 nm wavelength light generated by laser-pulsed tin plasma to pattern sub-7nm node silicon features.",
    formula: "Resolution CD = k1 · (λ / NA)",
    relatedTerms: ["High-NA EUV", "Rayleigh Criterion", "Photoresist"]
  },
  {
    term: "Clock Tree Synthesis",
    acronym: "CTS",
    category: "VLSI & Circuits",
    definition: "The automated physical design step that creates an optimized buffer network (H-Tree, Multi-Corner Mesh) to deliver the clock signal simultaneously to millions of flip-flops with minimal skew and insertion delay.",
    relatedTerms: ["Clock Skew", "Physical Design", "STA"]
  }
];
